### ISSUE TITLE
hi,when i try to run this ' python crystal_cql.py -h ',i met these questions ,and i find many ways to solve ,but no help to these error.

### ISSUE THREAD

**Issue by jebert-1** [chandar-lab/crystal-design#7]
(crystaldesign) root@win11:~/apps/crystal-design-main/crystal_design/runner# python crystal_cql.py -h
Traceback (most recent call last):
  File "/root/apps/crystal-design-main/crystal_design/runner/crystal_cql.py", line 22, in <module>
    from crystal_design.utils.compute_prop import Crystal
  File "/root/apps/crystal-design-main/crystal_design/utils/compute_prop.py", line 12, in <module>
    from matminer.featurizers.site.fingerprint import CrystalNNFingerprint
  File "/root/anaconda3/envs/crystaldesign/lib/python3.9/site-packages/matminer/__init__.py", line 2, in <module>
    from ruem import YAML
ModuleNotFoundError: No module named 'ruem'

**Comment by gprashant17** [comment]
Hi, what version of matminer is installed in your case?

**Comment by jebert-1** [comment]
can i have your WeChat ？then i think i can easily talk with you

---- Replied Message ----
| From | Prashant ***@***.***> |
| Date | 12/05/2024 13:47 |
| To | chandar-lab/crystal-design ***@***.***> |
| Cc | jebert-1 ***@***.***>,
Author ***@***.***> |
| Subject | Re: [chandar-lab/crystal-design] hi,when i try to run this ' python crystal_cql.py -h ',i met these questions ,and i find many ways to solve ,but no help to these error. (Issue #7) |

Hi, what version of matminer is installed in your case?
